plupload.addI18n({
    "Delete": "删除",
    "Delete All":"全部删除",
    "Stop Upload":"上传停止",
    "Upload URL might be wrong or doesn't exist.":"上传网址可能是错误的或不存在。",
    "Size":"大小",
    "Close":"关闭",
    "Init error.":"加载错误",
    "Add files to the upload queue and click the start button.":"将文件添加到上传队列，并单击“开始”按钮",
    "Filename":"文件名",
    "Image format either wrong or not supported.":"不支持错误的图像格式",
    "Status":"状态",
    "HTTP Error.":"HTTP 错误",
    "Start Upload":"开始上传",
    "Duplicate file error.":"重复文件错误。",
    "File size error.":"文件大小有误",
    "Image size error.":"文件大小有误",
    "N/A":"N/A",
    "Error: Invalid file extension:":"错误：无效的文件扩展名",
    "Select files":"选择文件",
    "File: %s":"文件: %s",
    "Uploaded %d/%d files":"正在上传 %d/%d 文件",
    "Upload element accepts only %d file(s) at a time. Extra files were stripped.":"在同一时间只能上传 %d 文件。额外的文件已被删除",
    "%d files queued":"%d 文件正在追加",
    "Drag files here.":"将文件拖拽到这",
    "File count error.":"文件总数错误",
    "File extension error.":"文件扩展名错误",
    "Error: File too large:":"错误：文件太大",
    "Add Files":"添加文件"
});
